# build.yaml
targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
        generate_for:
          - lib/i18n/*.json
      json_serializable:
        generate_for:
          - lib/models/*.dart
      freezed|freezed:
        generate_for:
          - lib/models/*.dart
      riverpod_annotation:
        generate_for:
          - lib/providers/*.dart
